### ISSUE TITLE
Panic Running on Linux

### ISSUE THREAD

**Issue by mike-stewart** [instrumenta/conftest#164]
I receive the following runtime error when executing a policy in a linux environment. I get the same error on go 1.12.x and 1.13.x as well as conftest 0.15 and 0.14.

Executing the same test on Mac with the same go/conftest version succeeds.

```
$ for x in `ls -1 clusters`; do kustomize build clusters/$x | conftest test -i yaml /dev/stdin || exit 1; done
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x8b8117]
goroutine 1 [running]:
github.com/open-policy-agent/opa/ast.(*Module).Copy(0x0, 0xc0005a3ad0)
	/go/pkg/mod/github.com/open-policy-agent/opa@v0.14.0/ast/policy.go:227 +0x47
github.com/open-policy-agent/opa/ast.(*Compiler).Compile(0xc0004a80c0, 0xc0005a3ad0)
	/go/pkg/mod/github.com/open-policy-agent/opa@v0.14.0/ast/compile.go:333 +0x107
github.com/instrumenta/conftest/pkg/policy.BuildCompiler(0xf79706, 0x6, 0x6, 0xf79706, 0x6)
	/home/circleci/project/pkg/policy/compiler.go:37 +0x29e
github.com/instrumenta/conftest/pkg/commands/test.NewTestCommand.func1(0xc000488a00, 0xc0003320f0, 0x1, 0x3)
	/home/circleci/project/pkg/commands/test/test.go:62 +0xf7
github.com/spf13/cobra.(*Command).execute(0xc000488a00, 0xc000332060, 0x3, 0x3, 0xc000488a00, 0xc000332060)
	/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:766 +0x2aa
github.com/spf13/cobra.(*Command).ExecuteC(0xc000488780, 0x0, 0xdfed20, 0xc00008e058)
	/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:852 +0x2ea
github.com/spf13/cobra.(*Command).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:800
main.main()
	/home/circleci/project/cmd/main.go:9 +0x27
```

**Comment by mike-stewart** [comment]
This appears to have been an intermittent issue - subsequent executions on my CI provider started passing after a few hours. I will close for now and re-open if it comes back.
