### ISSUE TITLE
Panic when passing empty rego file

### ISSUE THREAD

**Issue by KeisukeYamashita** [instrumenta/conftest#204]
## What

When you pass empty rego files with `-p ` flag, the conftest will run into panic. 
I will like to submit a PR for this to feedback users errors.

This panic is from OPA compiler but we should check beforehand of user input.

## Why

Showing users error messages are better than panic.

## How to reproduce

**OK**

```
$ go run main.go test -p examples/kubernetes/policy examples/kubernetes/deployment.yaml
PASS - examples/kubernetes/deployment.yaml - data.main.warn
FAIL - examples/kubernetes/deployment.yaml - hello-kubernetes must include Kubernetes recommended labels: https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/#labels 
FAIL - examples/kubernetes/deployment.yaml - Containers must not run as root in Deployment hello-kubernetes
FAIL - examples/kubernetes/deployment.yaml - Deployment hello-kubernetes must provide app/release labels for pod selectors
exit status 1
```

**Bad**

```
$ cat empty.rego
$ go run main.go test -p empty.rego  examples/kubernetes/deployment.yaml
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x179b527]

goroutine 1 [running]:
github.com/open-policy-agent/opa/ast.(*Module).Copy(0x0, 0xc0005d3930)
        /Users/keisuke.yamashita/go/1.13.0/pkg/mod/github.com/open-policy-agent/opa@v0.15.1/ast/policy.go:227 +0x47
github.com/open-policy-agent/opa/ast.(*Compiler).Compile(0xc0003975f0, 0xc0005d3930)
        /Users/keisuke.yamashita/go/1.13.0/pkg/mod/github.com/open-policy-agent/opa@v0.15.1/ast/compile.go:339 +0x107
github.com/instrumenta/conftest/policy.BuildCompiler(0xc0002ab520, 0x1, 0x1, 0x1, 0x1, 0x0)
        /Users/keisuke.yamashita/go/src/github.com/instrumenta/conftest/policy/compiler.go:29 +0x1f4
github.com/instrumenta/conftest/internal/commands.NewTestCommand.func2(0xc000452000, 0xc000278660, 0x1, 0x3, 0x0, 0x0)
        /Users/keisuke.yamashita/go/src/github.com/instrumenta/conftest/internal/commands/test.go:98 +0x4cd
github.com/spf13/cobra.(*Command).execute(0xc000452000, 0xc0002785d0, 0x3, 0x3, 0xc000452000, 0xc0002785d0)
        /Users/keisuke.yamashita/go/1.13.0/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:826 +0x460
github.com/spf13/cobra.(*Command).ExecuteC(0xc000035680, 0x0, 0x6f000, 0xc00003e0b8)
        /Users/keisuke.yamashita/go/1.13.0/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fb
github.com/spf13/cobra.(*Command).Execute(...)
```

When I pass something, it will success.

```
$ echo "package main" >> empty.rego
$ go run main.go test -p empty.rego examples/kubernetes/deployment.yaml
$ echo $?
=> 0
```

**Comment by Blokje5** [comment]
@KeisukeYamashita Thanks for reporting this and picking this up!
